# Generated by Django 4.2.14 on 2025-05-21 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0011_alter_pagecontent_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Short description of the project for chatbot responses')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_knowledge', to='chatbot_app.project')),
            ],
            options={
                'verbose_name': 'Chatbot Project Knowledge',
                'verbose_name_plural': 'Chatbot Project Knowledge',
            },
        ),
    ]
