# Generated by Django 4.2.14 on 2025-05-21 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0012_projectknowledge'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyInformation',
        ),
        migrations.RemoveField(
            model_name='customchatbotresponse',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='customchatbotresponse',
            name='project',
        ),
        migrations.DeleteModel(
            name='FAQ',
        ),
        migrations.RemoveField(
            model_name='projectknowledge',
            name='project',
        ),
        migrations.DeleteModel(
            name='CustomChatbotResponse',
        ),
        migrations.DeleteModel(
            name='ProjectKnowledge',
        ),
    ]
